# .travis.yml
sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27,stack-scrapy-1.0,stack-scrapy-1.1,stack-scrapy-1.2,stack-scrapy-1.3,stack-scrapy-1.4,stack-scrapy-1.5
    - python: 3.5
      env: TOXENV=py35,stack-scrapy-1.1-py3,stack-scrapy-1.2-py3
    - python: 3.6
      env: TOXENV=py36,stack-scrapy-1.3-py3,stack-scrapy-1.4-py3,stack-scrapy-1.5-py3
    - python: 3.8
      env: TOXENV=docs

install:
    - pip install -U tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: scrapinghub
  password:
    secure: rU/nBv26TZbZhO22zDeSWtQjmglSeG+ujWqfYUiLuAl4+JcNnQSFtqK14S4CZOLCjl8lfIJjZV073+X2zhy0AUVQrNlbVFRCwnAL9KsDG3s9ixGNhNdZB82R0+VdViI39M+Fhty8X1g0XhPmAoDz7Ol9G5Voyu5gCINQHFCaAxs=
  on:
    tags: true
    repo: scrapy-plugins/scrapy-crawlera
    condition: "$TOXENV =~ ^py27,"
