[tool.bumpversion]
current_version = "2.4.0"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "docs/news.rst"
search = "\\(unreleased\\)$"
replace = "({now:%Y-%m-%d})"
regex = true

[[tool.bumpversion.files]]
filename = "scrapy_zyte_smartproxy/__init__.py"

[[tool.bumpversion.files]]
filename = "setup.py"
